version: '3.7'

services:
  server:
    build:
      context: ./hacku_test
      dockerfile: Dockerfile
    container_name: notes_server
    ports:
      - 8000:8000
    volumes:
      - ./hacku_test/db.sqlite3:/app/db.sqlite3
